/**
 * Created by zhaofeng on 7/11/16.
 */
import keyMirror from 'key-mirror';

export default keyMirror({
    GET_ADVERTISEMENTS: 'GET_ADVERTISEMENTS',
    GET_DAILY_RECOMMEND: 'GET_DAILY_RECOMMEND',
    GET_SPECIAL_COLUMN: 'GET_SPECIAL_COLUMN',
    GET_LATEST_SINGERS: 'GET_LATEST_SINGERS',
    GET_SINGERS: 'GET_SINGERS',
    APPEARANCE_ERROR: 'APPEARANCE_ERROR',

    GET_RANK_OVERVIEW: 'GET_RANK_OVERVIEW',
    RANK_ERROR: 'RANK_ERROR',

    PLAY: 'PLAY',
    PAUSE: 'PAUSE',
    RESUME: 'RESUME'
})