/**
 * Created by zhaofeng on 7/11/16.
 */
import keyMirror from 'key-mirror';

export default keyMirror({
    GET_ADVERTISEMENTS: 'GET_ADVERTISEMENTS',
    GET_DAILY_RECOMMEND: 'GET_DAILY_RECOMMEND',
    GET_SPECIAL_COLUMN: 'GET_SPECIAL_COLUMN',
    GET_SPECIAL_COLUMNS: 'GET_SPECIAL_COLUMNS',
    GET_LATEST_SINGERS: 'GET_LATEST_SINGERS',
    GET_SINGERS: 'GET_SINGERS',
    APPEARANCE_ERROR: 'APPEARANCE_ERROR',

    GET_RANK_OVERVIEW: 'GET_RANK_OVERVIEW',
    GET_RANK_DETAIL: 'GET_RANK_DETAIL',
    RANK_ERROR: 'RANK_ERROR',

    GET_USER: 'GET_USER',
    GET_USER_SONGS: 'GET_USER_SONGS',

    GET_COLLECTIONS: 'GET_COLLECTIONS',
    GET_COLLECTION: 'GET_COLLECTION',
    GET_COLLECTION_SONG: 'GET_COLLECTION_SONG',

    GET_SQUARE: 'GET_SQUARE',

    PLAY: 'PLAY',
    PLAY2: 'PLAY2',
    CLEAR: 'CLEAR',
    ADD: 'ADD',
    PAUSE: 'PAUSE',
    RESUME: 'RESUME',
    ACTION: 'ACTION',
    NEXT: 'NEXT',
    PREVIOUS: 'PREVIOUS',
    CHANGE_PLAY_TYPE: 'CHANGE_PLAY_TYPE',
    GET_PERSONAL_INFO: 'GET_PERSONAL_INFO',
    GET_SONG_INFO: 'GET_SONG_INFO',

    GET_MY_SONGS: 'GET_MY_SONGS'
})