export const GET_STORE_CACHE_EVENT = 'GET_STORE_CACHE_EVENT';
export const SEND_STORE_CACHE_EVENT = 'SEND_STORE_CACHE_EVENT';
export const DOWNLOAD_SONG_EVENT = 'DOWNLOAD_SONG_EVENT';
export const DOWNLOAD_SONG_END_EVENT = 'DOWNLOAD_SONG_END_EVENT';
export const GET_SIGN_EVENT = 'GET_SIGN_EVENT';

export const INIT_SYSTEM_EVENT = 'INIT_SYSTEM_EVENT';
export const GO_BACK_EVENT = 'GO_BACK_EVENT';
export const GO_FORWARD_EVENT = 'GO_FORWARD_EVENT';

export const OPEN_LOGIN_WINDOW = 'OPEN_LOGIN_WINDOW';
export const LOGOUT_EVENT = 'LOGOUT_EVENT';
export const LOGIN_SUCCESS_EVENT = 'LOGIN_SUCCESS_EVENT';
export const SYNC_CACHE_EVENT = 'SYNC_CACHE_EVENT';
export const SYNC_LRC_EVENT = 'SYNC_LRC_EVENT';
