/**
 * Created by zhaofeng on 2016/8/1.
 */
import keyMirror from 'key-mirror';

export default keyMirror({
    GET_COLLECTIONS: 'GET_COLLECTIONS',
    GET_COLLECTION: 'GET_COLLECTION',
    GET_COLLECTION_SONG: 'GET_COLLECTION_SONG',
    ADD_TO_MY_COLLECTIONS: 'ADD_TO_MY_COLLECTIONS',
    REMOVE_FROM_MY_COLLECTIONS: 'REMOVE_FROM_MY_COLLECTIONS'
})