name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install yarn -g
      - run: yarn install
      - run: npm run make
      - name: Qiniu Upload
        uses: miaowing/action-qiniu-upload@v0.0.3
        with:
          access_key: ${{ secrets.QINIU_ACCESS_KEY }}
          secret_key: ${{ secrets.QINIU_SECRET_KEY }}
          bucket: i5sing
          source_dir: ./out/make
          dest_dir: /packages
          ignore: RELEASES
